### ISSUE TITLE
mysqlclient instead pymysql?

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/agentarchives#18]
Archivematica is likely going to use mysqlclient instead of pymysql, see #400 for more details. Should we be consistent with this in related projects like this one?

**Comment by mistydemeo** [comment]
Sure! We haven't had a production release of Archivematica using this yet, so as long as there aren't compatibility problems there's not much impact to switching at this point.

**Comment by mistydemeo** [comment]
See #19!

**Comment by sevein** [comment]
wop! thank you!
