### ISSUE TITLE
ValueError: Invalid header value b'c199575edf58088f\n' from an Atom server

### ISSUE THREAD

**Issue by axfelix** [artefactual-labs/agentarchives#45]
Hi,

I'm trying to use this library to make a `client.add_digital_object()` call to an Atom server, and I'm getting `ValueError: Invalid header value b'c199575edf58088f\n'. Does this just mean that I'm trying to post to a record that doesn't exist, or is there something wrong with the connection handling at that point?

**Comment by axfelix** [comment]
Ping @sevein

**Comment by sevein** [comment]
@axfelix, it's possible that there is a line break at the end of your API key and that's what's causing Python's standard library to raise that exception.

E.g. this works for me:

```
>>> import requests
>>> requests.get('https://www.artefactual.com', headers={'Foo': 'Bar'})
```

But this doesn't:

```
>>> import requests
>>> requests.get('https://www.artefactual.com', headers={'Foo': 'Bar\n'})
```

Try passing your key as `c199575edf58088f` instead of `c199575edf58088f\n`.

**Comment by axfelix** [comment]
Ah, geez, good catch!
