### ISSUE TITLE
mysqlclient library installation issue on macos

### ISSUE THREAD

**Issue by J4bbi** [artefactual-labs/agentarchives#46]
When trying to install agentarchives it would fail because mysqlclient wouldn't install:

see: https://medium.com/@MrWeeble/homebrew-on-mac-and-pythons-mysqlclient-ea44fa300e70

solution is :

env LDFLAGS="-I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib" pip install mysqlclient==1.3.12

**Comment by sevein** [comment]
Thanks @J4bbi. I'm curious to hear what do you expect from this project to happen to address the issue. Should we update the README with the link you've shared?

**Comment by J4bbi** [comment]
@sevein Well this is obviously a limited dependency issue. The reason I posted it is that it took me some time to research it to find this solution. So my intention is only to share in case it might save someone else time.

Mentioning it in the readme sounds like a good idea. I'll make PRs.

**Comment by sevein** [comment]
Thank you!

**Comment by sevein** [comment]
Fixed in https://github.com/artefactual-labs/agentarchives/pull/52 by @J4bbi.
