### ISSUE TITLE
Agentarchives does not log out of ArchivesSpace

### ISSUE THREAD

**Issue by J4bbi** [artefactual-labs/agentarchives#47]
Whereas agentarchives logs into an ArchivesSpace server and establishes a session https://github.com/artefactual-labs/agentarchives/blob/a310e00d76c58816baedc008ac1cf84a1603d4c8/agentarchives/archivesspace/client.py#L63-L80 it does not explicitly log out but rather timeouts (I assume).

Logging out is a very simple API post if you include the session:
https://archivesspace.github.io/archivesspace/api/#post-logout

Creating a logout function should be very easy then. I can do that and make a PR.

**Comment by sevein** [comment]
> Creating a logout function should be very easy then. I can do that and make a PR.

Yes, please! I'd be happy to CR.
